### ISSUE TITLE
warnings in tests

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#70] opened 2019-05-09 12:38 UTC
```
pizza_cutter/des_pizza_cutter/tests/test_se_image_resample.py::test_se_image_resample_smoke
  /direct/astro+u/esheldon/git/pizza-cutter/pizza_cutter/memmappednoise.py:55: RuntimeWarning: divide by zero encountered in true_divide
    size=(sx, sy)) * np.sqrt(1.0 / wgt)

pizza_cutter/des_pizza_cutter/tests/test_se_image_slice_io.py::test_se_image_slice_read
  /direct/astro+u/esheldon/git/pizza-cutter/pizza_cutter/memmappednoise.py:55: RuntimeWarning: divide by zero encountered in true_divide
    size=(sx, sy)) * np.sqrt(1.0 / wgt)

pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs.py::test_se_image_wcs_esutil_array
  /gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/scipy/optimize/minpack.py:163: RuntimeWarning: The iteration is not making good progress, as measured by the 
    improvement from the last ten iterations.
    warnings.warn(msg, RuntimeWarning)
```

the first two are bad, dividing by zero.

The last is also probably bad, but I haven't investigated.

**Comment by beckermr** [comment] 2019-05-09 12:44
Ugh I missed these. Good catch!

**Comment by esheldon** [comment] 2019-05-09 12:46
Are they suppressed on circleci?

**Comment by beckermr** [comment] 2019-05-09 12:47
They don't cause failures. We can turn them into failures if we want to. The divide by zero might be a good candidate for this.

https://docs.pytest.org/en/latest/warnings.html

**Comment by beckermr** [comment] 2019-05-14 01:27
I'm still unable to reproduce this last warning locally. Any hints or ideas here @esheldon?

**Comment by esheldon** [comment] 2019-05-14 13:35
Maybe it has to do with some local differences in the machines we are using.

**Comment by beckermr** [comment] 2020-05-28 21:21
closing this for now

**Closed by beckermr** 2020-05-28 21:21 UTC
