### ISSUE TITLE
metadetect fails

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#118] opened 2019-05-15 18:23 UTC
```
(pizza) [esheldon@astro0001 meds-test-y5] run-metadetect-on-slices --config=/astro/u/esheldon/git/pizza-cutter/config_files/metadetect.yaml --output-path=mdet.fits --seed=3412 DES0406-5414_i_des-pizza-slices-y5_meds-pizza-slices.fits.fz 
# of slices: 1521
slice range: [0, 1521)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
zero weight observation found, skipping
Traceback (most recent call last):
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/bin/run-metadetect-on-slices", line 4, in <module>
    __import__('pkg_resources').run_script('pizza-cutter==0.1.0', 'run-metadetect-on-slices')
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/run-metadetect-on-slices", line 86, in <module>
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/run-metadetect-on-slices", line 82, in main
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/run-metadetect-on-slices", line 71, in _call
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/metadetect/run_metadetect.py", line 158, in run_metadetect
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/metadetect/run_metadetect.py", line 75, in _do_metadetect
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/metadetect/metadetect.py", line 12, in do_metadetect
    md.go()
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/metadetect/metadetect.py", line 53, in go
    odict=self._get_all_metacal()
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/metadetect/metadetect.py", line 131, in _get_all_metacal
    **self['metacal']
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/ngmix/metacal.py", line 94, in get_all_metacal
    odict= _get_all_metacal_fixnoise(obs, step=step, **kw)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/ngmix/metacal.py", line 228, in _get_all_metacal_fixnoise
    obsdict       = _get_all_metacal(obs, step=step, **kw)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/ngmix/metacal.py", line 142, in _get_all_metacal
    odict=_make_metacal_mb_obs_list_dict(obs, step, **kw)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/ngmix/metacal.py", line 1732, in _make_metacal_mb_obs_list_dict
    new_dict=_init_mb_obs_list_dict(list(odict.keys()))
AttributeError: 'NoneType' object has no attribute 'keys'

```

**Comment by esheldon** [comment] 2019-05-15 18:23
at bnl the meds file is
```
/gpfs/mnt/gpfs02/astro/desdata/esheldon/lensing/des-lensing/test-pizza-cutter/meds-test-y5/DES0406-5414_i_des-pizza-slices-y5_meds-pizza-slices.fits.fz
```

**Comment by beckermr** [comment] 2019-05-15 19:01
Which config did you use?

**Comment by beckermr** [comment] 2019-05-15 19:10
you need to use this config: https://github.com/beckermr/pizza-cutter/blob/master/config_files/metadetect.yaml

It appears you passed the other ones in since they would be missing the metacal section.

**Comment by beckermr** [comment] 2019-05-15 20:03
The command is working fine for me on my local meds files. The one you linked has negative weights which appears to be a bug or file corruption. I cannot reproduce locally.

**Comment by esheldon** [comment] 2019-05-16 01:18
that's the meds file I used to make all the images we viewed earlier today, and yes I did use that config

**Comment by esheldon** [comment] 2019-05-16 01:21
I'm trying on another meds file and its working, so probably I accidentally overwrote it when I was testing, and I didn't finish the creation of the file, probably even killed it right away.

but due to reserving the file it looks big as usual

**Comment by beckermr** [comment] 2019-05-16 02:53
Sounds good. Closing

**Closed by beckermr** 2019-05-16 02:53 UTC

**Comment by esheldon** [comment] 2019-05-16 13:43
so even after fixing the weight map problem we are getting failures in metadetect due to no cutouts being returned
